@echo off
echo Cleaning frontend cache...
cd /d "%~dp0"
echo Removing .next directory...
rmdir /s /q .next
echo Removing node_modules...
rmdir /s /q node_modules
echo Reinstalling dependencies...
call npm install
echo Done! Please restart with 'npm run dev'.
pause
